config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root 'home#index'

  # Routes for "clerks" resource
  # GET /clerks
  resources :clerks, only: [:index]

  # POST /populate
  post '/populate', to: 'clerks#populate'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/clerk.rb
class Clerk < ApplicationRecord
  VALID_PICTURE_TYPES = %w[image/jpeg image/png].freeze
  VALID_PICTURE_SIZE = 5.megabytes

  has_one_attached :picture

  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :email, presence: true, length: { maximum: 128 },
                    format: { with: URI::MailTo::EMAIL_REGEXP },
                    uniqueness: { case_sensitive: false }
  validates :phone, presence: true, length: { maximum: 32 }
  validates :registration_date, presence: true

  validate :acceptable_picture

  before_save { email.downcase! if email_changed? }

  # Create Clerk records from users fetched from the RandomUser API. If a user
  # fails to be created, the error is logged and the process continues.
  #
  # @option options [Integer] :size (5) The number of users to fetch and create.
  # @return [Hash] A hash containing the following keys:
  #  - :success_count [Integer] The number of successfully created Clerk records.
  #  - :total_count [Integer] The total number of Clerk records that were attempted to be created.
  def self.create_from_random_user(size: 5)
    users = RandomUser.fetch_users(size: size)
    success_count = create_clerks_and_enqueue_pictures(users)

    if success_count < size
      3.times do
        users = RandomUser.fetch_users(size: size - success_count)
        success_count += create_clerks_and_enqueue_pictures(users)

        break if success_count >= size
      end
    end

    Rails.logger.info("Successfully created #{success_count}/#{size} Clerk records")

    # Return the number of successfully created Clerk records and the total
    { success_count: success_count, total_count: size }
  end

  private

  def acceptable_picture
    return unless picture.attached?

    errors.add(:picture, 'is too big') unless picture.byte_size < VALID_PICTURE_SIZE
    errors.add(:picture, 'must be JPEG or PNG') unless VALID_PICTURE_TYPES.include?(picture.content_type)
  end

  def self.create_clerks_and_enqueue_pictures(users)
    success_count = 0

    users.each do |user|
      attributes = RandomUserSerializer.to_clerk_attributes(user)

      clerk = Clerk.new(attributes.except(:picture_url))

      if clerk.save
        # Download the picture in the background
        ClerkPictureDownloadJob.perform_later(clerk.id, attributes[:picture_url])

        Rails.logger.info("Successfully created Clerk record for #{clerk.email}")
        success_count += 1
      else
        errors = clerk.errors.full_messages.join(', ')
        Rails.logger.error("Failed to create Clerk record for #{attributes[:email]}: #{errors}")
      end
    end

    success_count
  end

  private_class_method :create_clerks_and_enqueue_pictures
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/clerks_controller.rb
class ClerksController < ApplicationController
  DEFAULT_PAGE_SIZE = 10
  MAX_PAGE_SIZE = 100

  # TODO: Rails provides by default CSRF protection for POST requests.
  # However, we need to disable it for the `populate` action (for now) as we
  # intend to (possibly) use it from an API client.
  #
  # Consider providing a separate authentication mechanism for API clients
  # (e.g. API tokens) and re-enabling CSRF protection for the `populate` action.
  protect_from_forgery except: :populate

  # GET /clerks
  def index
    params = index_params

    @clerks = Clerk.with_attached_picture.order(registration_date: :desc, id: :desc)

    if params[:email]
      # No need to downcase email column; it's already downcase-d in the model
      @clerks = @clerks.where(email: params[:email].downcase)
    end

    if params[:ending_before]
      ending_before_attrs = Clerk.where(id: params[:ending_before]).
        pick(:registration_date, :id)

      if ending_before_attrs.present?
        @clerks = @clerks.where('(registration_date, id) > (?, ?)', ending_before_attrs[0], ending_before_attrs[1])
        # Reverse the order of Clerks if we're fetching the previous page to
        # get the immediate preceding Clerks, not the preceding starting from
        # the start (i.e. the least recent of the most recent).
        @clerks = @clerks.reverse_order
      else
        # If the Clerk with the given ID doesn't exist, return an empty result
        @clerks = Clerk.none
      end
    elsif params[:starting_after]
      starting_after_attrs = Clerk.where(id: params[:starting_after]).
        pick(:registration_date, :id)

      @clerks =
        if starting_after_attrs.present?
          @clerks.where('(registration_date, id) < (?, ?)', starting_after_attrs[0], starting_after_attrs[1])
        else
          Clerk.none
        end
    end

    @page_size = params[:limit].to_i
    @page_size = @page_size.positive? && @page_size <= MAX_PAGE_SIZE ? @page_size : DEFAULT_PAGE_SIZE

    # Fetch one more Clerk than the page size to determine if there's a next
    # or previous page
    @clerks = @clerks.limit(@page_size + 1)

    # Convert the ActiveRecord::Relation to an Array to avoid any extra
    # queries to the database
    @clerks = @clerks.to_a
    @fetched_records_count = @clerks.size

    # Remove the extra Clerk from the collection
    @clerks = @clerks.take(@page_size)

    # Reverse the order of Clerks if we're fetching the previous page to
    # save a few %#@$%! from the user :)
    @clerks.reverse! if params[:ending_before]

    set_pagination_state!

    respond_to do |format|
      format.html
      format.json { render json: @clerks }
    end
  end

  # POST /populate
  def populate
    resp = Clerk.create_from_random_user(size: 5000)
    success = resp[:success_count]
    total = resp[:total_count]

    if success == total
      message = "All #{total} users were created successfully."
      flash[:success] = message
      status = 'success'
    elsif success.positive?
      message = "#{success} out of #{total} users were created successfully."
      flash[:warning] = message
      status = 'warning'
    else
      message = 'No users were created.'
      flash[:error] = message
      status = 'failure'
    end

    respond_to do |format|
      format.html { redirect_to root_path }
      format.json { render json: resp.merge(message: message, status: status) }
    end
  end

  private

  def index_params
    params.permit(:limit, :starting_after, :ending_before, :email)
  end

  def set_pagination_state!
    params = index_params

    # TODO: Improve this logic (email is unique, so we can't have more than one)
    if !@fetched_records_count.positive? || params[:email].present?
      @has_previous_page = false
      @has_next_page = false

      return
    end

    if params[:starting_after].blank? && params[:ending_before].blank?
      # We are on the first page, no previous exists
      @has_previous_page = false
      @has_next_page = @fetched_records_count > @page_size
    elsif params[:starting_after].present?
      # We are moving forward, so there is a previous page
      @has_previous_page = true
      @has_next_page = @fetched_records_count > @page_size
    elsif params[:ending_before].present?
      # We are moving backward, so there is a next page
      @has_previous_page = @fetched_records_count > @page_size
      @has_next_page = true
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index; end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/clerks_helper.rb
module ClerksHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/clerks/index.html.erb
<div class="clerks-index-page">
  <a href="/" class="homepage-link">Home</a>

  <h1>Clerks</h1>

  <table>
    <thead>
    <tr>
      <th>Picture</th>
      <th>First Name</th>
      <th>Last Name</th>
      <th>Email</th>
      <th>Phone</th>
      <th>Registration Date</th>
    </tr>
    </thead>

    <tbody>
    <% @clerks.each do |clerk| %>
      <tr>
        <% if clerk.picture.attached? %>
          <td><%= image_tag url_for(clerk.picture), size: '100x100', alt: 'Clerk Picture' %></td>
        <% else %>
          <td><%= image_tag 'clerk/picture.jpg', size: '100x100', alt: 'Default Picture' %></td>
        <% end %>
        <td><%= clerk.id %> | <%= clerk.first_name %></td>
        <td><%= clerk.last_name %></td>
        <td><%= clerk.email %></td>
        <td><%= clerk.phone %></td>
        <td><%= clerk.registration_date.to_formatted_s(:long) %></td>
      </tr>
    <% end %>
    </tbody>
  </table>

  <div class="pagination-buttons">
    <% if @has_previous_page %>
      <%= link_to 'Previous Page', clerks_path(ending_before: @clerks.first.id, limit: params[:limit]), class: "btn btn-primary" %>
    <% else %>
      <%= button_to 'Previous Page', nil, class: "btn btn-primary disabled", disabled: true, method: :get %>
    <% end %>
    <% if @has_next_page %>
      <%= link_to 'Next Page', clerks_path(starting_after: @clerks.last.id, limit: params[:limit]), class: "btn btn-primary" %>
    <% else %>
      <%= button_to 'Next Page', nil, class: "btn btn-primary disabled", disabled: true, method: :get %>
    <% end %>
  </div>
</div>

app/views/home/index.html.erb
<div class="home-page">
  <h1 class="centered-title">Welcome to Clerks-API</h1>

  <div class="flash-container">
    <% flash.each do |key, value| %>
      <div class="alert alert-<%= key %>">
        <%= value %>
      </div>
    <% end %>
  </div>

  <div class="action-buttons">
    <a href="<%= clerks_path %>" class="btn btn-action">Show Clerks 👩‍💼</a>
    <a href="<%= populate_path %>" class="btn btn-action" data-turbo-method="post">Populate Clerks 🚀</a>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ClerksApi</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>